[project]
name = "learningfromscratch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.10.8",
    "notebook>=7.5.0",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.2",
    "torch>=2.9.1",
]
